name: Build Windows EXE

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile main.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@latest
        with:
          name: executable
          path: dist/main.exe

